name: Docker Cleanup

on: delete

jobs:
  cleanup_branch:
    if: startsWith(github.event.ref_type, 'branch') == true
    runs-on: ubuntu-latest
    steps:
      - name: Sanitize branch docker tag
        uses: frabert/replace-string-action@master
        id: dockertag
        with:
          pattern: '[:\.\/]+'
          string: "${{ github.event.ref }}"
          replace-with: '-'
          flags: 'g'

      - name: Get GitHub Package Release ID
        run: |
          echo "::set-env name=VERSION_ID::$(curl -X POST \
          -H "Accept: application/vnd.github.packages-preview+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -d "{\"query\":\"query {repository(owner:\\\""l3uddz"\\\", name:\\\""nabarr"\\\") {packages(names:[\\\""nabarr"\\\"], first:1) {edges{node{id, name, version(version:\\\""${{ tag }}"\\\"){id, version}}}}}}\"}" \
          https://api.github.com/graphql | jq '.data.repository.packages.edges[].node.version.id')"

      - uses: actions/delete-package-versions@v1
        with:
          package-version-ids: '${{ VERSION_ID }}'